# Add or edit clues here. Keys are the ANSWERS (uppercase), values are the clues shown to players.

CLUES = {
    # General Roman
    "NANCY": "First name of the telescope's namesake",
    "GRACE": "Middle name shared by the telescope and its namesake",
    "CORONAGRAPH": "Instrument designed to block starlight and reveal exoplanets",
    "MICROLENSING": "Planet-finding technique that relies on gravity-bent light beams",
    "TRANSIT": "Planet-finding technique that relies on planets 'eclipsing' their host stars",
    "EXOPLANETS": "Worlds orbiting stars beyond our Sun",
    "DARKENERGY": "Mysterious phenomenon driving cosmic acceleration",
    "DARKMATTER": "Invisible substance whose gravity shapes galaxies",
    "SUPERNOVA": "Exploding star used to probe cosmic expansion",
    "INFRARED": "Region of the spectrum where Roman primarily observes",
    "WFI": "Abbreviation for Roman's Wide Field Instrument",
    "MILKYWAY": "Galaxy whose bulge Roman will repeatedly survey",
    "BULGE": "Dense central region of the Milky Way targeted by one of Roman's time-domain surveys",
    "TIMEDOMAIN": "Type of astronomy focused on changing and transient phenomena",


    # Miscellaneous
    "NASA": "Agency operating the Roman mission",
    "ASTRONOMER": "Nancy Grace Roman's profession",
    "GODDARD": "NASA center managing the Roman mission",
    "STSCI": "Institute that will help operate Roman science programs",
    "BALTIMORE": "Home city of the SOC (STScI)",
    "PASADENA": "Home city of the SSC (IPAC)",
    "EIGHTEEN": "Number of H4RG detector arrays in Roman's focal plane",
    "H4RG": "New-generation detector whose name encodes four thousand pixels on a side",
    "READNOISE": "Quantity reduced through up-the-ramp sampling",
    "DARKCURRENT": "Signal present even when no photons arrive",
    "GAIN": "Conversion factor between electrons and recorded counts",
    "FLATFIELD": "Calibration used to correct pixel-to-pixel sensitivity variations",
    "ZEROPOINT": "Photometric calibration constant",
    "SATURATION": "What happens when a source is too bright",
    "CROSSTALK": "Electronic contamination between detector channels",
    "DECONVOLUTION": "Analysis method attempting to undo PSF blurring",
    "HLWAS": "Acronym for Roman's flagship High Latitude Wide Area Survey",
    "HLDS": "Community survey acronym focused on the distant universe",
    "DITHER": "Small telescope offset repeated many times to improve imaging",
    "MOSAIC": "Product formed from many overlapping Roman pointings",
    "DEPTH": "Survey quantity often traded against area",
    "AREA": "Survey quantity often traded against depth",
    "CADENCE": "Frequency with which Roman revisits a field",
    "PHOTOZ": "Abbreviated estimate of galaxy distance from colors alone",
    "SPECZ": "Distance estimate obtained from spectroscopy",
    "COMPLETENESS": "Fraction of detectable sources successfully recovered",
    "BLENDING": "Crowded-field problem especially relevant in Galactic Bulge surveys",
    "DIFFRACTION": "Physical phenomenon ultimately setting Roman's angular resolution",
    "NONDESTRUCTIVE": "Type of detector read performed repeatedly during an exposure",
    "UPTHERAMP": "Sampling technique used to suppress read noise",

    # Roman mission & history
    "WFIRST": "Roman's former name: Wide Field Infrared Survey Telescope",
    "ROMAN": "Surname of NASA's first Chief of Astronomy, now the telescope's name",
    "FLAGSHIP": "Class of large NASA science mission; Roman joins Hubble and JWST in this tier",
    "DECADAL": "___ Survey: astronomy community's ten-year planning document that prioritized Roman",
    "CHIEF": "Nancy Grace Roman's title at NASA; she was the first to hold it for astronomy",
    "LAGRANGE": "French mathematician whose second gravitational balance point is Roman's destination",
    "HALO": "Type of orbit Roman traces around its gravitational balance point",

    # Related telescopes & partners
    "HUBBLE": "Nancy Grace Roman was given the nickname 'the mother of ____'",
    "JWST": "Infrared predecessor already operating at L2; Roman will join it there",
    "EUCLID": "ESA dark energy mission with overlapping science goals to Roman",
    "RUBIN": "Vera C. ___ Observatory: Roman's planned ground-based partner for wide-field surveys",

    # Science concepts
    "REDSHIFT": "Stretching of light from a receding source; Roman uses it to map cosmic structure",
    "WEAKLENSING": "Subtle shape distortions of galaxies used to map dark matter distribution",
    "STANDARDCANDLE": "Object of known luminosity used to measure cosmic distances",
    "MAGNIFICATION": "Brightening of a background source during a microlensing event",
    "LIGHTCURVE": "Time-series plot of brightness; key data product for time-domain surveys",
    "TRANSIENT": "Short-lived astronomical event; Roman's cadence is designed to catch these",
    "CEPHEID": "Pulsating variable star used as a rung on the cosmic distance ladder",
    "PARALLAX": "Stellar (geometric)distance method using Earth's annual orbital motion",
    "REIONIZATION": "Cosmic epoch when the first stars cleared the universe's neutral hydrogen fog",
    "QUASAR": "Distant, luminous active galactic nucleus; Roman will discover many",
    "FILAMENT": "Thread-like structure connecting galaxy clusters in the cosmic web",
    "VOID": "Large empty region in the large-scale structure mapped by Roman",
    "EXPANSION": "Roman will measure the rate of cosmic ___ using Type Ia supernovae",
    "LAMBDA": "Greek letter denoting the cosmological constant in Einstein's equations",
    "COSMOLOGY": "Study of the universe's origin, evolution, and fate; a primary Roman mission driver",
    "EINSTEIN": "Physicist who's theory of general relativity underpins many of Roman's science goals, including microlensing and weak lensing",

    # Instrument & technical
    "RESOLUTION": "Angular sharpness Roman achieves: about 0.1 arcseconds per pixel",
    "GRISM": "Spectroscopic element in Roman's WFI that combines a grating and a prism",
    "PRISM": "Optical element providing Roman's low-resolution slitless spectroscopy mode",
    "SLITLESS": "Type of spectroscopy Roman performs without restricting light to a narrow slit",
    "SPECTROSCOPY": "Technique that disperses light into its component wavelengths",
    "MULTIPLEX": "Spectroscopic advantage: observing many objects at once in a wide field",
    "POINTSPREAD": "___ function (PSF): the 2D image profile of a point source through Roman's optics",
}
