# Extended filler word bank — ~1,500 common English words (3–8 letters)
# Merged with secrets.toml filler_clues at app startup; secrets entries
# take priority when the same word appears in both sources.

FILLER_BANK: dict[str, str] = {

    # ── 3-letter words ──────────────────────────────────────────────────────
    "ACE": "Card above king",
    "ACT": "Stage performance",
    "ADD": "Sum together",
    "AGE": "Period of time",
    "AID": "Give assistance",
    "AIM": "Take a target",
    "AIR": "Atmosphere we breathe",
    "ALE": "Hoppy brew",
    "ALP": "High mountain pasture",
    "ANT": "Colony insect",
    "APE": "Tailless primate",
    "ARC": "Curved line",
    "ARK": "Biblical vessel",
    "ARM": "Limb from shoulder",
    "ART": "Creative expression",
    "ASH": "Fire residue",
    "AWE": "Reverential wonder",
    "AXE": "Chopping tool",
    "AYE": "Affirmative vote",
    "BAD": "Not good",
    "BAG": "Carry-all sack",
    "BAR": "Rod or tavern",
    "BAT": "Flying mammal",
    "BAY": "Coastal inlet",
    "BED": "Place to sleep",
    "BET": "Wager on outcome",
    "BIG": "Large in size",
    "BOW": "Front of a ship",
    "BOX": "Rectangular container",
    "BOY": "Young male",
    "BUD": "Flower before blooming",
    "BUS": "Public transit vehicle",
    "BUY": "Purchase",
    "CAB": "Taxi",
    "CAN": "Tin container",
    "CAP": "Brimless hat",
    "CAR": "Automobile",
    "CAT": "Feline pet",
    "COB": "Corn on the ___",
    "COD": "North Atlantic fish",
    "COG": "Gear tooth",
    "COT": "Folding bed",
    "COW": "Dairy animal",
    "CRY": "Shed tears",
    "CUB": "Young bear",
    "CUE": "Billiard stick",
    "CUP": "Drinking vessel",
    "CUT": "Slice through",
    "DAB": "Light touch",
    "DAM": "River barrier",
    "DAY": "24-hour period",
    "DEN": "Animal lair",
    "DEW": "Morning moisture",
    "DIG": "Excavate soil",
    "DIM": "Low in brightness",
    "DIP": "Brief immersion",
    "DOE": "Female deer",
    "DOG": "Loyal pet",
    "DOT": "Small spot",
    "DUE": "Owed amount",
    "DUO": "Pair of performers",
    "DYE": "Coloring agent",
    "EAR": "Hearing organ",
    "EEL": "Snakelike fish",
    "EGG": "Oval food item",
    "ELK": "Large deer",
    "ELM": "Shade tree",
    "EMU": "Australian flightless bird",
    "END": "Final point",
    "ERA": "Historical period",
    "EWE": "Female sheep",
    "EYE": "Vision organ",
    "FAD": "Passing craze",
    "FAN": "Cooling device",
    "FAR": "Great distance",
    "FAT": "Body tissue",
    "FIG": "Sweet purple fruit",
    "FIN": "Fish wing",
    "FLY": "Winged insect",
    "FOE": "Enemy",
    "FOG": "Dense mist",
    "FOX": "Clever canine",
    "FRY": "Cook in oil",
    "FUN": "Enjoyment",
    "FUR": "Animal coat",
    "GAP": "Opening or space",
    "GAS": "Vaporous matter",
    "GEM": "Precious stone",
    "GIN": "Juniper-flavored spirit",
    "GNU": "African wildebeest",
    "GUM": "Chewing substance",
    "GUN": "Firearm",
    "GUY": "Fellow",
    "HAM": "Cured pork",
    "HAT": "Head covering",
    "HEN": "Female chicken",
    "HEW": "Chop with axe",
    "HIT": "Strike hard",
    "HOP": "Short jump",
    "HOT": "High temperature",
    "HUB": "Central point",
    "HUE": "Color shade",
    "HUG": "Warm embrace",
    "HUM": "Monotone sound",
    "HUT": "Small shelter",
    "ICE": "Frozen water",
    "ILL": "Sick",
    "INN": "Roadside lodging",
    "ION": "Charged particle",
    "IRE": "Intense anger",
    "IVY": "Climbing vine",
    "JAB": "Quick punch",
    "JAM": "Fruit preserve",
    "JAR": "Glass container",
    "JAW": "Lower face bone",
    "JAY": "Blue songbird",
    "JET": "Fast aircraft",
    "JOB": "Occupation",
    "JOT": "Write briefly",
    "JOY": "Happiness",
    "JUG": "Pitcher with handle",
    "KEG": "Small barrel",
    "KID": "Young goat or child",
    "KIN": "Family relations",
    "LAD": "Young boy",
    "LAP": "Seated thigh area",
    "LAW": "Legal rule",
    "LAY": "Place down flat",
    "LEA": "Grassy meadow",
    "LEG": "Lower limb",
    "LID": "Container cover",
    "LIP": "Edge of mouth",
    "LOG": "Felled tree trunk",
    "LOT": "Plot of land",
    "LOW": "Near the ground",
    "MAD": "Angry or insane",
    "MAP": "Geographic chart",
    "MAT": "Floor covering",
    "MEN": "Adult males",
    "MOB": "Unruly crowd",
    "MOW": "Cut the grass",
    "MUG": "Large cup",
    "NIT": "Lice egg",
    "NOD": "Head gesture",
    "NUT": "Shelled seed",
    "OAK": "Acorn-bearing tree",
    "OAR": "Rowing paddle",
    "OAT": "Grain for porridge",
    "ODE": "Lyric poem",
    "OIL": "Lubricating fluid",
    "ORB": "Spherical object",
    "ORE": "Metal-bearing rock",
    "OWE": "Be in debt",
    "OWL": "Nocturnal bird",
    "PAD": "Cushioned surface",
    "PAL": "Good friend",
    "PAN": "Cooking vessel",
    "PAR": "Standard level",
    "PAT": "Gentle tap",
    "PAW": "Animal foot",
    "PAY": "Give wages",
    "PEA": "Green pod vegetable",
    "PEG": "Wooden pin",
    "PEN": "Writing instrument",
    "PET": "Domestic animal",
    "PIE": "Baked pastry dish",
    "PIG": "Farm animal",
    "PIN": "Fastening spike",
    "PIT": "Deep hole",
    "POD": "Seed casing",
    "POT": "Cooking vessel",
    "PUB": "British tavern",
    "PUN": "Wordplay",
    "PUT": "Place in position",
    "RAG": "Torn cloth",
    "RAM": "Male sheep",
    "RAP": "Sharp knock",
    "RAT": "Small rodent",
    "RAW": "Uncooked",
    "RAY": "Beam of light",
    "RED": "Primary color",
    "RIG": "Equipment setup",
    "RIM": "Outer edge",
    "RIP": "Tear apart",
    "ROD": "Thin straight pole",
    "ROE": "Fish eggs",
    "ROT": "Decay process",
    "ROW": "Line of seats",
    "RUG": "Floor mat",
    "RUM": "Caribbean spirit",
    "RUN": "Move quickly",
    "RUT": "Groove in ground",
    "RYE": "Grain for bread",
    "SAG": "Droop downward",
    "SAP": "Tree fluid",
    "SAW": "Cutting tool",
    "SAY": "Speak words",
    "SEA": "Saltwater expanse",
    "SET": "Group of items",
    "SEW": "Stitch fabric",
    "SKI": "Snow glide",
    "SKY": "Overhead atmosphere",
    "SOB": "Weep audibly",
    "SOD": "Grass turf",
    "SOW": "Female pig",
    "SOY": "Bean crop",
    "SPA": "Health retreat",
    "SPY": "Secret agent",
    "SUN": "Our star",
    "TAB": "Small flap",
    "TAN": "Light brown",
    "TAP": "Light knock",
    "TAR": "Dark sticky substance",
    "TAX": "Government levy",
    "TEA": "Hot beverage",
    "TIN": "Metal container",
    "TIP": "Top point",
    "TOE": "Foot digit",
    "TON": "Unit of weight",
    "TOP": "Highest part",
    "TOW": "Pull behind",
    "TOY": "Plaything",
    "TUG": "Pull sharply",
    "URN": "Decorative vessel",
    "USE": "Put to work",
    "VAN": "Cargo vehicle",
    "VAT": "Large tank",
    "VEX": "Irritate",
    "VIA": "By way of",
    "VIE": "Compete",
    "VOW": "Solemn pledge",
    "WAD": "Thick bundle",
    "WAR": "Armed conflict",
    "WAX": "Candle material",
    "WEB": "Spider structure",
    "WIG": "Hair piece",
    "WIN": "Achieve victory",
    "WIT": "Sharp intelligence",
    "WOE": "Deep sorrow",
    "WOK": "Asian cooking pan",
    "YAK": "Himalayan bovine",
    "YAM": "Sweet potato",
    "YEN": "Japanese currency",
    "YEW": "Evergreen tree",
    "ZAP": "Strike suddenly",
    "ZIP": "Move quickly",
    "ZOO": "Animal park",

    # ── 4-letter words ──────────────────────────────────────────────────────
    "ABLE": "Capable",
    "ACHE": "Dull pain",
    "ACRE": "Land measure",
    "AIDE": "Helper",
    "ALOE": "Succulent plant",
    "ALTO": "Low singing voice",
    "ANTE": "Poker stake",
    "ARCH": "Curved structure",
    "ARIA": "Opera solo",
    "BACK": "Rear side",
    "BAIL": "Release from custody",
    "BALE": "Bundle of hay",
    "BALM": "Soothing ointment",
    "BAND": "Musical group",
    "BANE": "Cause of misery",
    "BANG": "Loud explosion",
    "BARE": "Uncovered",
    "BARK": "Tree covering",
    "BARN": "Farm building",
    "BASK": "Lie in warmth",
    "BATH": "Cleansing soak",
    "BEAD": "Small round ball",
    "BEAM": "Ray of light",
    "BEAN": "Legume vegetable",
    "BEAR": "Large forest mammal",
    "BEAT": "Rhythmic pulse",
    "BEET": "Red root vegetable",
    "BELT": "Waist strap",
    "BILE": "Digestive fluid",
    "BIRD": "Feathered creature",
    "BITE": "Teeth action",
    "BLOT": "Ink stain",
    "BLUE": "Sky color",
    "BOAR": "Wild pig",
    "BOAT": "Small watercraft",
    "BOLD": "Courageous",
    "BOLT": "Door fastener",
    "BOND": "Strong connection",
    "BONE": "Skeletal structure",
    "BOOK": "Reading material",
    "BOOM": "Loud noise",
    "BORE": "Make weary",
    "BUFF": "Polishing motion",
    "BULB": "Light source",
    "BULK": "Large mass",
    "BULL": "Male bovine",
    "BURN": "Catch fire",
    "BUZZ": "Insect hum",
    "CAFE": "Coffee house",
    "CAGE": "Enclosure",
    "CAKE": "Baked dessert",
    "CALF": "Young cow",
    "CALM": "Peaceful",
    "CAMP": "Outdoor shelter",
    "CANE": "Walking stick",
    "CAPE": "Short cloak",
    "CARD": "Stiff paper",
    "CARE": "Concern",
    "CART": "Small wagon",
    "CASH": "Physical money",
    "CAST": "Throw or mold",
    "CAVE": "Natural cavern",
    "CELL": "Basic life unit",
    "CHAT": "Casual talk",
    "CHIP": "Small fragment",
    "CHOP": "Cut roughly",
    "CLAM": "Bivalve shellfish",
    "CLAP": "Applaud",
    "CLAW": "Sharp animal nail",
    "CLAY": "Moldable earth",
    "CLUE": "Puzzle hint",
    "COAL": "Black fuel rock",
    "COAT": "Outer garment",
    "COIL": "Spiral shape",
    "COLD": "Low temperature",
    "COLT": "Young horse",
    "CONE": "Geometric shape",
    "COOK": "Prepare food",
    "COOL": "Pleasantly cold",
    "CORD": "Thin rope",
    "CORE": "Central part",
    "CORK": "Bottle stopper",
    "CORN": "Grain crop",
    "COVE": "Sheltered bay",
    "CREW": "Work team",
    "CROP": "Harvested plants",
    "CROW": "Black bird",
    "CUBE": "Six-sided solid",
    "CURB": "Pavement edge",
    "CURE": "Remedy",
    "CURL": "Spiral wave",
    "DALE": "Open valley",
    "DAMP": "Slightly wet",
    "DARE": "Bold challenge",
    "DARK": "Without light",
    "DART": "Quick movement",
    "DASH": "Sprint",
    "DAWN": "Sunrise",
    "DEAL": "Business agreement",
    "DECK": "Ship's floor",
    "DEER": "Forest herbivore",
    "DENT": "Surface depression",
    "DESK": "Writing table",
    "DICE": "Cube for games",
    "DIET": "Eating plan",
    "DINE": "Eat dinner",
    "DIRT": "Soil",
    "DISH": "Serving plate",
    "DOME": "Rounded roof",
    "DOVE": "Peace symbol bird",
    "DOWN": "Soft feathers",
    "DRAG": "Pull along",
    "DRAW": "Create a picture",
    "DRIP": "Slow drop",
    "DROP": "Let fall",
    "DRUM": "Percussion instrument",
    "DUAL": "Double",
    "DUEL": "Combat for two",
    "DUNE": "Sand hill",
    "DUSK": "Evening twilight",
    "DUST": "Fine dry particles",
    "EARL": "British nobleman",
    "EARN": "Receive wages",
    "EAST": "Sunrise direction",
    "EDGE": "Outer boundary",
    "EDIT": "Revise text",
    "EVEN": "Flat and level",
    "EVIL": "Morally bad",
    "FACE": "Front of head",
    "FACT": "Verified truth",
    "FADE": "Lose brightness",
    "FAKE": "Not genuine",
    "FALL": "Descend",
    "FAME": "Wide recognition",
    "FAST": "Quick speed",
    "FATE": "Destiny",
    "FEAR": "Dread",
    "FEAT": "Impressive act",
    "FEED": "Provide food",
    "FEEL": "Sense by touch",
    "FELT": "Past of feel",
    "FERN": "Leafy plant",
    "FILE": "Organized folder",
    "FILL": "Make full",
    "FILM": "Movie or coating",
    "FINE": "Penalty fee",
    "FISH": "Aquatic vertebrate",
    "FIZZ": "Effervescence",
    "FLAG": "National emblem",
    "FLAT": "Level surface",
    "FLAW": "Defect",
    "FLEA": "Tiny jumping insect",
    "FLIP": "Turn over",
    "FLOW": "Move smoothly",
    "FOAM": "Airy froth",
    "FOLD": "Crease over",
    "FOLK": "Common people",
    "FOND": "Having affection",
    "FOOD": "Nourishment",
    "FOOL": "Act silly",
    "FORD": "River crossing",
    "FORK": "Eating utensil",
    "FORM": "Shape or type",
    "FORT": "Military stronghold",
    "FOUL": "Offensive odor",
    "FOWL": "Domesticated bird",
    "FREE": "At liberty",
    "FROG": "Amphibian",
    "FUEL": "Energy source",
    "FULL": "Completely filled",
    "FUND": "Pool of money",
    "GALE": "Strong wind",
    "GAME": "Competitive activity",
    "GATE": "Entrance barrier",
    "GAZE": "Long look",
    "GEAR": "Mechanical part",
    "GILL": "Fish breathing organ",
    "GLEE": "Delight",
    "GLOW": "Emit warmth or light",
    "GLUE": "Adhesive",
    "GNAW": "Chew persistently",
    "GOAT": "Horned farm animal",
    "GONG": "Metal percussion disk",
    "GOWN": "Long dress",
    "GRAB": "Seize quickly",
    "GRAY": "Between black and white",
    "GRID": "Network of lines",
    "GRIN": "Broad smile",
    "GRIP": "Firm hold",
    "GRIT": "Determination",
    "GULF": "Large bay",
    "GULL": "Seabird",
    "GUST": "Sudden wind burst",
    "HACK": "Rough cut",
    "HAIL": "Frozen precipitation",
    "HALF": "One of two parts",
    "HALL": "Wide corridor",
    "HALT": "Stop moving",
    "HAND": "End of arm",
    "HANG": "Suspend above",
    "HARD": "Firm texture",
    "HARE": "Wild rabbit relative",
    "HARM": "Cause injury",
    "HARP": "Stringed instrument",
    "HASH": "Chopped mixture",
    "HAZE": "Atmospheric blur",
    "HEAD": "Top of body",
    "HEAL": "Recover from injury",
    "HEAP": "Disorderly pile",
    "HEAT": "Thermal energy",
    "HEEL": "Rear of foot",
    "HERD": "Animal group",
    "HIGH": "Far above",
    "HIKE": "Long walk",
    "HILL": "Elevated ground",
    "HINT": "Indirect suggestion",
    "HIRE": "Employ",
    "HOLD": "Keep in hand",
    "HOLE": "Opening",
    "HOME": "Place of residence",
    "HOOK": "Curved fastener",
    "HORN": "Wind instrument",
    "HOSE": "Flexible tube",
    "HOST": "Party organizer",
    "HULL": "Grain outer layer",
    "HUNT": "Search for prey",
    "HUSK": "Dry outer shell",
    "ICON": "Symbol or image",
    "IDEA": "Mental concept",
    "IDLE": "Not working",
    "IRON": "Metallic element",
    "ISLE": "Small island",
    "ITCH": "Skin irritation",
    "JADE": "Green gemstone",
    "JAIL": "Prison",
    "JAZZ": "Music genre",
    "JOLT": "Sudden shock",
    "JUMP": "Leap upward",
    "JUST": "Morally right",
    "KEEN": "Sharp or eager",
    "KELP": "Sea algae",
    "KILL": "End a life",
    "KIND": "Gentle and caring",
    "KING": "Male monarch",
    "KITE": "Flying toy",
    "KNOB": "Rounded protrusion",
    "KNOT": "Tied rope",
    "LACE": "Decorative fabric",
    "LACK": "Be without",
    "LAIR": "Animal hideout",
    "LAKE": "Inland body of water",
    "LAMB": "Young sheep",
    "LAME": "Unable to walk well",
    "LAND": "Solid ground",
    "LANE": "Narrow road",
    "LARK": "Songbird",
    "LASH": "Strike with whip",
    "LATE": "After expected time",
    "LAVA": "Molten rock",
    "LAWN": "Grass area",
    "LEAD": "Heavy metal element",
    "LEAF": "Plant organ",
    "LEAN": "Incline or thin",
    "LEAP": "Jump across",
    "LEND": "Let borrow",
    "LIME": "Citrus fruit",
    "LIMP": "Uneven walk",
    "LINE": "Long thin mark",
    "LINK": "Connect together",
    "LION": "African big cat",
    "LIST": "Written series",
    "LIVE": "Be alive",
    "LOAD": "Heavy cargo",
    "LOAM": "Rich garden soil",
    "LOAN": "Borrowed money",
    "LOCK": "Security device",
    "LOFT": "Upper room",
    "LOOM": "Weaving machine",
    "LOOP": "Circular shape",
    "LORE": "Traditional knowledge",
    "LURE": "Entice",
    "LUSH": "Luxuriantly green",
    "MAID": "Female servant",
    "MAIL": "Postal delivery",
    "MAIN": "Principal",
    "MAKE": "Construct",
    "MANE": "Lion's neck hair",
    "MARE": "Female horse",
    "MARK": "Written symbol",
    "MAST": "Ship's vertical pole",
    "MATE": "Companion",
    "MAZE": "Labyrinth",
    "MEAL": "Occasion for eating",
    "MEAN": "Intend or average",
    "MEAT": "Animal flesh",
    "MELT": "Turn to liquid",
    "MESH": "Interlaced structure",
    "MILD": "Gentle",
    "MILE": "Distance unit",
    "MILL": "Grinding machine",
    "MIND": "Thinking organ",
    "MINE": "Underground excavation",
    "MINT": "Fresh herb",
    "MIST": "Light fog",
    "MOAT": "Defensive ditch",
    "MOLD": "Fungal growth",
    "MOLE": "Burrowing animal",
    "MOON": "Earth's satellite",
    "MOOR": "Open wetland",
    "MOSS": "Tiny ground plant",
    "MUCK": "Wet mud",
    "MULE": "Donkey hybrid",
    "MUSE": "Source of inspiration",
    "MUSK": "Animal scent",
    "NAIL": "Metal fastener",
    "NAME": "Identifying word",
    "NAPE": "Back of neck",
    "NECK": "Body part below head",
    "NEST": "Bird dwelling",
    "NEWT": "Small salamander",
    "NODE": "Connection point",
    "NOOK": "Cozy corner",
    "NORM": "Standard",
    "NOTE": "Short message",
    "OVAL": "Egg-shaped",
    "OVEN": "Cooking appliance",
    "OVER": "Above",
    "PACE": "Walking speed",
    "PACK": "Bundle together",
    "PAGE": "Book leaf",
    "PAIL": "Bucket",
    "PAIR": "Set of two",
    "PALE": "Light in color",
    "PALM": "Tropical tree",
    "PARK": "Public green space",
    "PATH": "Narrow way",
    "PAVE": "Cover with stone",
    "PAWN": "Chess piece",
    "PEAK": "Mountain top",
    "PEAR": "Bell-shaped fruit",
    "PEAT": "Compressed bog matter",
    "PEEL": "Remove outer layer",
    "PELT": "Animal skin",
    "PERK": "Extra benefit",
    "PEST": "Troublesome insect",
    "PIKE": "Spear or fish",
    "PILE": "Heap of items",
    "PINE": "Evergreen tree",
    "PINK": "Light red color",
    "PIPE": "Hollow tube",
    "PLOD": "Walk heavily",
    "PLOT": "Plan or story",
    "PLOW": "Soil-turning tool",
    "PLUM": "Purple stone fruit",
    "POEM": "Lyrical writing",
    "POLE": "Long thin rod",
    "PORE": "Skin opening",
    "PORT": "Harbor",
    "POSE": "Adopt a position",
    "POST": "Mail or pole",
    "PULL": "Draw toward",
    "PUMP": "Force fluid through",
    "PURE": "Uncontaminated",
    "PUSH": "Apply forward force",
    "RACK": "Storage frame",
    "RAGE": "Intense anger",
    "RAID": "Sudden attack",
    "RAIN": "Falling water",
    "RAKE": "Garden tool",
    "RAMP": "Inclined surface",
    "RANK": "Position in hierarchy",
    "RASP": "Rough file",
    "REEF": "Underwater rock ridge",
    "REEL": "Spool of film",
    "REIN": "Horse control strap",
    "RENT": "Payment for use",
    "RICE": "Grain staple",
    "RIDE": "Travel on",
    "RIFT": "Split or crack",
    "RING": "Circular band",
    "RIOT": "Public disorder",
    "RIPE": "Ready to eat",
    "RISE": "Move upward",
    "RISK": "Chance of loss",
    "ROAD": "Paved path",
    "ROAM": "Wander freely",
    "ROAR": "Loud cry",
    "ROBE": "Long garment",
    "ROCK": "Stony mineral",
    "ROLE": "Part in play",
    "ROLL": "Revolve",
    "ROOF": "Building top",
    "ROOM": "Interior space",
    "ROOT": "Plant anchor",
    "ROPE": "Twisted fiber",
    "ROSE": "Thorny flower",
    "ROTE": "Repetitive learning",
    "ROVE": "Wander",
    "RUIN": "Crumbled remains",
    "RULE": "Governing principle",
    "RUSH": "Move hurriedly",
    "RUST": "Iron oxide",
    "SAFE": "Secure",
    "SAGA": "Long heroic tale",
    "SAGE": "Wise person",
    "SAIL": "Cloth for wind power",
    "SALT": "Mineral seasoning",
    "SAND": "Fine grains",
    "SANE": "Mentally sound",
    "SEAL": "Marine mammal",
    "SEAM": "Sewn join",
    "SHED": "Outdoor storage",
    "SHIN": "Lower leg front",
    "SHIP": "Large vessel",
    "SHOT": "Fired projectile",
    "SHOW": "Display or exhibit",
    "SILK": "Fine thread fabric",
    "SILL": "Window base",
    "SILO": "Grain tower",
    "SILT": "Fine river sediment",
    "SINK": "Submerge",
    "SKIP": "Light hop",
    "SLAM": "Shut with force",
    "SLAP": "Open-hand strike",
    "SLIM": "Slender",
    "SLIP": "Lose footing",
    "SLOP": "Spill clumsily",
    "SLOW": "Not fast",
    "SNAG": "Catch on a point",
    "SNAP": "Break suddenly",
    "SNIP": "Cut with scissors",
    "SOIL": "Earth layer",
    "SOLE": "Bottom of shoe",
    "SONG": "Musical composition",
    "SOOT": "Black carbon dust",
    "SORE": "Painful spot",
    "SORT": "Arrange by type",
    "SOUL": "Spiritual essence",
    "SOUP": "Liquid food",
    "SOUR": "Tart flavor",
    "SPAN": "Width across",
    "SPAR": "Practice fighting",
    "SPIN": "Rotate fast",
    "SPIT": "Eject from mouth",
    "SPOT": "Marked location",
    "STEM": "Plant stalk",
    "STEP": "Single stair",
    "STEW": "Slow-cooked dish",
    "STIR": "Mix around",
    "STUB": "Short remnant",
    "SUCH": "Of that kind",
    "SUIT": "Matching outfit",
    "SULK": "Pout silently",
    "SURF": "Ocean waves",
    "SWAN": "Graceful white bird",
    "SWAY": "Swing gently",
    "TAIL": "Rear appendage",
    "TALE": "Narrative story",
    "TALK": "Verbal communication",
    "TALL": "Great in height",
    "TAME": "Not wild",
    "TANG": "Sharp flavor",
    "TASK": "Assigned work",
    "TEAL": "Blue-green color",
    "TEAR": "Rip apart",
    "TERM": "Period of time",
    "TEST": "Evaluation",
    "THIN": "Narrow width",
    "TIDE": "Ocean water level",
    "TILE": "Flat surface piece",
    "TILL": "Cultivate soil",
    "TILT": "Lean sideways",
    "TIRE": "Lose energy",
    "TOAD": "Warty amphibian",
    "TOIL": "Hard labor",
    "TOLL": "Road charge",
    "TOMB": "Burial vault",
    "TOME": "Large book",
    "TONE": "Sound quality",
    "TOOL": "Work implement",
    "TOUR": "Sightseeing trip",
    "TRAP": "Snare",
    "TREE": "Tall woody plant",
    "TRIM": "Neat border",
    "TRIO": "Group of three",
    "TRIP": "Short journey",
    "TUCK": "Fold neatly",
    "TUFT": "Small cluster",
    "TUSK": "Long curved tooth",
    "TWIN": "One of two alike",
    "VALE": "Valley",
    "VANE": "Wind direction arrow",
    "VASE": "Flower holder",
    "VAST": "Immense",
    "VEIL": "Face covering",
    "VEIN": "Blood vessel",
    "VEST": "Sleeveless garment",
    "VINE": "Climbing plant",
    "VOID": "Empty space",
    "WADE": "Walk through water",
    "WAIL": "Loud cry",
    "WANE": "Decrease",
    "WARD": "Hospital division",
    "WARM": "Slightly hot",
    "WARP": "Twist out of shape",
    "WASP": "Stinging insect",
    "WAVE": "Undulating motion",
    "WEAK": "Lacking strength",
    "WELD": "Join by heat",
    "WELL": "Deep water hole",
    "WEST": "Sunset direction",
    "WHIP": "Strike with lash",
    "WICK": "Candle core",
    "WIDE": "Broad measurement",
    "WILD": "Not tame",
    "WILT": "Droop from heat",
    "WIND": "Moving air",
    "WINE": "Fermented grape drink",
    "WING": "Limb for flight",
    "WINK": "Close one eye",
    "WIRE": "Metal thread",
    "WISE": "Having wisdom",
    "WISH": "Desired outcome",
    "WOLF": "Wild canid",
    "WORM": "Burrowing creature",
    "WREN": "Tiny songbird",
    "YELL": "Shout loudly",
    "YOKE": "Ox harness",
    "YORE": "Days of old",
    "ZEAL": "Enthusiastic devotion",
    "ZEST": "Enthusiastic energy",
    "ZINC": "Metallic element",
    "ZONE": "Defined area",
    "ZOOM": "Move rapidly",

    # ── 5-letter words ──────────────────────────────────────────────────────
    "ABBOT": "Monastery head",
    "ABIDE": "Tolerate",
    "ABYSS": "Deep chasm",
    "ACUTE": "Sharp or severe",
    "ADAPT": "Adjust to change",
    "ADEPT": "Highly skilled",
    "ADORN": "Decorate",
    "AFOOT": "In progress",
    "AGAVE": "Desert plant",
    "AGILE": "Quick and nimble",
    "AGLOW": "Radiant with light",
    "AGONY": "Intense suffering",
    "AISLE": "Walkway between rows",
    "ALBUM": "Collection of photos",
    "ALGAE": "Aquatic plant",
    "ALIGN": "Line up",
    "ALOFT": "High in the air",
    "ALONE": "By oneself",
    "ALONG": "By the side of",
    "ALOOF": "Distant manner",
    "ALOUD": "Spoken audibly",
    "ALTAR": "Sacred table",
    "ALTER": "Change",
    "AMAZE": "Astonish",
    "AMBER": "Fossil resin",
    "AMBLE": "Leisurely walk",
    "AMEND": "Revise",
    "AMONG": "In the middle of",
    "AMPLE": "More than enough",
    "AMUSE": "Entertain",
    "ANGEL": "Divine messenger",
    "ANGER": "Annoyance",
    "ANGLE": "Corner measurement",
    "ANKLE": "Foot joint",
    "ANNEX": "Attached wing",
    "ANTIC": "Playful behavior",
    "ANVIL": "Blacksmith's block",
    "ARBOR": "Garden bower",
    "ARDOR": "Passionate intensity",
    "ARENA": "Sports venue",
    "ARGON": "Noble gas",
    "ARRAY": "Orderly arrangement",
    "ARROW": "Projectile with tip",
    "ARSON": "Deliberate fire-setting",
    "ASHEN": "Pale gray",
    "ASTER": "Star-shaped flower",
    "ATOLL": "Ring-shaped island",
    "ATONE": "Make amends",
    "ATTIC": "Top floor room",
    "AUDIT": "Financial review",
    "AUGUR": "Predict from signs",
    "AVAIL": "Be of use",
    "BACON": "Cured pork strips",
    "BADGE": "Identifying emblem",
    "BAKER": "Bread maker",
    "BANJO": "Plucked instrument",
    "BASIN": "Shallow bowl",
    "BATCH": "Group produced at once",
    "BEACH": "Sandy shore",
    "BEARD": "Facial hair",
    "BEAST": "Wild animal",
    "BELLE": "Beautiful woman",
    "BENCH": "Long seat",
    "BERRY": "Small juicy fruit",
    "BLAZE": "Bright fire",
    "BLEAK": "Dreary",
    "BLEND": "Mix smoothly",
    "BLISS": "Perfect happiness",
    "BLOCK": "Solid cube",
    "BLOOD": "Life fluid",
    "BLOOM": "Come into flower",
    "BOARD": "Flat wooden plank",
    "BOXER": "Fighting athlete",
    "BRACE": "Strengthen",
    "BRAID": "Plaited strand",
    "BRAKE": "Stopping device",
    "BRAND": "Trade mark",
    "BRAVE": "Showing courage",
    "BRAWL": "Rough fight",
    "BRINK": "Very edge",
    "BROIL": "Cook under heat",
    "BROOK": "Small stream",
    "BROOD": "Offspring group",
    "BROOM": "Sweeping brush",
    "BROTH": "Thin soup",
    "BRUSH": "Cleaning tool",
    "BRUTE": "Savage creature",
    "BUGLE": "Military horn",
    "BULLY": "Intimidate",
    "BUNCH": "Cluster",
    "CABIN": "Small wooden house",
    "CAMEL": "Desert animal",
    "CANAL": "Man-made waterway",
    "CANDY": "Sweet confection",
    "CARGO": "Ship's load",
    "CAROL": "Christmas song",
    "CEDAR": "Aromatic wood",
    "CHANT": "Repeated song",
    "CHAOS": "Utter disorder",
    "CHARM": "Magical appeal",
    "CHASE": "Pursue",
    "CHEEK": "Side of face",
    "CHESS": "Strategy board game",
    "CHEST": "Treasure box",
    "CHIME": "Bell sound",
    "CHOIR": "Singing group",
    "CHORD": "Musical notes together",
    "CINCH": "Easy task",
    "CIVIC": "City related",
    "CIVIL": "Polite",
    "CLAMP": "Gripping device",
    "CLANG": "Loud metal sound",
    "CLASS": "Group of students",
    "CLEFT": "Split in rock",
    "CLIFF": "Steep rock face",
    "CLIMB": "Go upward",
    "CLINK": "Glass touching sound",
    "CLOAK": "Concealing garment",
    "CLOCK": "Time measuring device",
    "CLOSE": "Near",
    "CLOUD": "Water vapor mass",
    "CLOWN": "Circus performer",
    "COAST": "Shoreline",
    "COBRA": "Hooded snake",
    "COMET": "Icy space visitor",
    "CORAL": "Reef-building organism",
    "COUNT": "Enumerate",
    "COURT": "Judicial chamber",
    "COVER": "Put over",
    "CRACK": "Split open",
    "CRAFT": "Skilled trade",
    "CRANE": "Tall wading bird",
    "CREAK": "Squeaky sound",
    "CREEK": "Narrow stream",
    "CREST": "Top of wave",
    "CRISP": "Firm and dry",
    "CROSS": "Angry",
    "CROWD": "Dense group",
    "CROWN": "Royal headpiece",
    "CRUMB": "Bread fragment",
    "CRUSH": "Compress with force",
    "CRYPT": "Underground vault",
    "CYCLE": "Recurring sequence",
    "DAILY": "Every day",
    "DAIRY": "Milk products",
    "DAISY": "White-petaled flower",
    "DANCE": "Rhythmic movement",
    "DECAY": "Gradual rot",
    "DECOY": "Lure for birds",
    "DELTA": "Greek letter",
    "DENSE": "Closely packed",
    "DEPOT": "Transportation hub",
    "DERBY": "Horse race",
    "DIGIT": "Finger or number",
    "DIZZY": "Feeling of spinning",
    "DODGE": "Avoid swiftly",
    "DRAFT": "First version",
    "DRAIN": "Remove liquid",
    "DRAWL": "Slow speech",
    "DREAD": "Fear greatly",
    "DREAM": "Sleeping vision",
    "DREGS": "Sediment",
    "DRILL": "Boring tool",
    "DRINK": "Consume liquid",
    "DRIVE": "Operate vehicle",
    "DRONE": "Unmanned aircraft",
    "DROOL": "Salivate",
    "DROOP": "Hang downward",
    "DROWN": "Die in water",
    "EAGLE": "Large raptor",
    "EARLY": "Before expected time",
    "EARTH": "Our planet",
    "EASEL": "Artist's stand",
    "EBONY": "Dark black wood",
    "ELDER": "Older person",
    "ELITE": "Select few",
    "EMBER": "Glowing coal",
    "EMOTE": "Show emotion",
    "EMPTY": "Containing nothing",
    "ENACT": "Make into law",
    "ENJOY": "Take pleasure in",
    "ERODE": "Wear away",
    "ESSAY": "Short written piece",
    "EVADE": "Avoid cleverly",
    "EXACT": "Precise",
    "EXALT": "Praise highly",
    "EXILE": "Forced removal",
    "FABLE": "Moral short story",
    "FACET": "One aspect",
    "FAIRY": "Magical creature",
    "FAITH": "Belief without proof",
    "FANCY": "Elaborate",
    "FARCE": "Absurd comedy",
    "FEAST": "Large meal",
    "FEIGN": "Pretend",
    "FENCE": "Boundary barrier",
    "FERRY": "Water transport",
    "FLAME": "Fire light",
    "FLANK": "Side of body",
    "FLARE": "Sudden blaze",
    "FLASH": "Brief bright light",
    "FLASK": "Small bottle",
    "FLECK": "Small spot",
    "FLEET": "Group of ships",
    "FLESH": "Body tissue",
    "FLOCK": "Group of birds",
    "FLOOD": "Overflow of water",
    "FLOOR": "Bottom surface",
    "FLOSS": "Dental thread",
    "FLOUR": "Ground grain",
    "FLUTE": "Wind instrument",
    "FOGGY": "Covered in mist",
    "FORGE": "Shape metal by heat",
    "FOYER": "Entrance hall",
    "FRAIL": "Fragile",
    "FRAME": "Supporting structure",
    "FRAUD": "Deceptive trick",
    "FRESH": "Not stale",
    "FRIAR": "Religious brother",
    "FROND": "Fern leaf",
    "FROST": "Ice crystals",
    "FROTH": "Foam on liquid",
    "FRUIT": "Plant seed holder",
    "FUNGI": "Mushroom kingdom",
    "FUNKY": "Having strong smell",
    "GAUZE": "Thin fabric",
    "GENRE": "Category of art",
    "GHOST": "Spirit apparition",
    "GIRTH": "Circumference",
    "GIVEN": "Provided",
    "GLAND": "Secreting organ",
    "GLARE": "Harsh bright light",
    "GLASS": "Transparent material",
    "GLEAM": "Faint shine",
    "GLIDE": "Smooth movement",
    "GLOOM": "Partial darkness",
    "GLORY": "Great honor",
    "GLOSS": "Shiny surface",
    "GLOVE": "Hand covering",
    "GORGE": "Deep ravine",
    "GOURD": "Hollow vegetable",
    "GRACE": "Elegant poise",
    "GRADE": "Level or mark",
    "GRAIN": "Cereal seed",
    "GRANT": "Award funds",
    "GRASP": "Grip tightly",
    "GRAZE": "Feed on grass",
    "GREED": "Excessive desire",
    "GREET": "Welcome",
    "GROAN": "Pained sound",
    "GROVE": "Small tree cluster",
    "GROWL": "Low threatening sound",
    "GUARD": "Protect",
    "GUISE": "Outward appearance",
    "GUSTO": "Vigorous enjoyment",
    "HABIT": "Regular practice",
    "HAVEN": "Safe place",
    "HEART": "Pumping organ",
    "HEDGE": "Shrub boundary",
    "HEIST": "Robbery",
    "HERBS": "Culinary plants",
    "HERON": "Wading bird",
    "HORDE": "Large crowd",
    "HOUND": "Hunting dog",
    "HUMAN": "People",
    "HUMOR": "Sense of comedy",
    "HYDRA": "Multi-headed monster",
    "IDEAL": "Perfect standard",
    "IDIOM": "Figurative phrase",
    "IMPLY": "Suggest indirectly",
    "INGOT": "Metal casting",
    "IRONY": "Contrary outcome",
    "IVORY": "Elephant tusk material",
    "JUDGE": "Legal arbiter",
    "JUICE": "Liquid from fruit",
    "JUMBO": "Extra large",
    "KARMA": "Cause and effect",
    "KAYAK": "Paddled boat",
    "KNAVE": "Dishonest man",
    "KNEEL": "Rest on knees",
    "KNOLL": "Small rounded hill",
    "KNOWN": "Widely understood",
    "LANCE": "Long spear",
    "LANKY": "Tall and thin",
    "LARGE": "Big in size",
    "LASER": "Focused light beam",
    "LATCH": "Door fastener",
    "LAYER": "Thickness of material",
    "LEDGE": "Narrow shelf",
    "LEGAL": "Permitted by law",
    "LEVEL": "Flat and even",
    "LIGHT": "Visible radiation",
    "LILAC": "Purple flower",
    "LIVER": "Digestive organ",
    "LLAMA": "South American camel",
    "LODGE": "Mountain shelter",
    "LOGIC": "Reasoned thinking",
    "LOYAL": "Faithful",
    "LUCID": "Clearly expressed",
    "LYRIC": "Song verse",
    "MANGO": "Tropical fruit",
    "MANOR": "Country estate",
    "MAGIC": "Supernatural power",
    "MAPLE": "Syrup-producing tree",
    "MARCH": "Rhythmic walk",
    "MARSH": "Wetland area",
    "MAXIM": "General truth",
    "MEDAL": "Award disk",
    "MELEE": "Confused fight",
    "MERCY": "Compassionate relief",
    "MERIT": "Deserved credit",
    "METAL": "Hard mineral element",
    "MIRTH": "Amusement",
    "MISER": "Greedy hoarder",
    "MOIST": "Slightly wet",
    "MOOSE": "Large deer",
    "MOSSY": "Covered in moss",
    "MOUND": "Pile of earth",
    "MOUNT": "Climb upward",
    "MOURN": "Grieve",
    "MOUSE": "Small rodent",
    "MOUTH": "Opening for speech",
    "MULCH": "Garden covering",
    "MURAL": "Wall painting",
    "MURKY": "Dark and dirty",
    "NADIR": "Lowest point",
    "NERVE": "Signaling tissue",
    "NICHE": "Suitable position",
    "NIGHT": "Dark hours",
    "NOBLE": "Of high rank",
    "NOISY": "Loud",
    "NUDGE": "Gentle push",
    "NYMPH": "Nature spirit",
    "OCEAN": "Vast salt water",
    "OFFER": "Propose",
    "ONSET": "Beginning",
    "OPTIC": "Relating to vision",
    "OXIDE": "Oxygen compound",
    "PANEL": "Flat section",
    "PANSY": "Colorful garden flower",
    "PASTE": "Adhesive mixture",
    "PAUSE": "Brief stop",
    "PEACH": "Fuzzy stone fruit",
    "PEARL": "Lustrous gem",
    "PEDAL": "Foot lever",
    "PERCH": "Resting place",
    "PETAL": "Flower leaf",
    "PILOT": "Aircraft operator",
    "PINCH": "Squeeze between fingers",
    "PITCH": "Musical tone",
    "PIXEL": "Screen dot",
    "PLAID": "Tartan pattern",
    "PLAIN": "Flat treeless land",
    "PLANT": "Growing organism",
    "PLAZA": "Open public square",
    "PLUCK": "Pull out",
    "PLUMB": "Exactly vertical",
    "PLUME": "Ornamental feather",
    "POACH": "Cook in liquid",
    "POISE": "Graceful balance",
    "POPPY": "Red flower",
    "POUCH": "Small bag",
    "PRANK": "Practical joke",
    "PRAWN": "Large shrimp",
    "PRESS": "Apply pressure",
    "PRIDE": "Satisfaction in achievement",
    "PRIME": "Best quality",
    "PRIOR": "Before",
    "PRIVY": "Aware of secrets",
    "PRIZE": "Award for winning",
    "PROBE": "Investigation tool",
    "PROOF": "Evidence",
    "PROSE": "Ordinary writing",
    "PROUD": "Feeling self-respect",
    "PROWL": "Move stealthily",
    "PRUNE": "Trim branches",
    "PSALM": "Sacred song",
    "QUEEN": "Female monarch",
    "QUERY": "Question",
    "QUEST": "Long search",
    "QUILL": "Feather pen",
    "QUIRK": "Odd habit",
    "RABBI": "Jewish religious leader",
    "RALLY": "Group gathering",
    "RAVEN": "Large black bird",
    "REALM": "Kingdom",
    "REGAL": "Royal",
    "RELAX": "Rest",
    "REPAY": "Pay back",
    "RESIN": "Plant secretion",
    "REVEL": "Celebrate noisily",
    "RIDGE": "Elevated crest",
    "RIGID": "Stiff",
    "RIPEN": "Become ready",
    "RIVER": "Flowing water",
    "RIVET": "Metal fastener",
    "ROOST": "Bird sleeping spot",
    "ROWDY": "Noisy behavior",
    "ROYAL": "Belonging to monarchy",
    "RUGBY": "Contact ball sport",
    "RULER": "Measuring stick",
    "SABER": "Curved sword",
    "SCOUT": "Explore ahead",
    "SEIZE": "Take forcibly",
    "SHARD": "Broken fragment",
    "SHARK": "Predatory fish",
    "SHAWL": "Shoulder wrap",
    "SHEAR": "Cut fleece",
    "SHORE": "Water's edge",
    "SHOUT": "Call loudly",
    "SHOVE": "Push roughly",
    "SHRUB": "Woody plant",
    "SIEGE": "Military blockade",
    "SIEVE": "Straining mesh",
    "SIGHT": "Visual perception",
    "SIGMA": "Greek letter",
    "SKIFF": "Small flat boat",
    "SKILL": "Learned ability",
    "SKIRT": "Lower garment",
    "SKULL": "Bone head case",
    "SLANG": "Informal language",
    "SLASH": "Cut with sweep",
    "SLICK": "Smooth and glossy",
    "SLIME": "Wet sticky substance",
    "SLOTH": "Slow-moving mammal",
    "SMART": "Intelligent",
    "SMEAR": "Spread untidily",
    "SMILE": "Happy expression",
    "SMOKE": "Fire vapor",
    "SNARE": "Trap",
    "SNARL": "Growl with teeth",
    "SNEAK": "Move stealthily",
    "SNORE": "Sleep breathing sound",
    "SOLAR": "Relating to sun",
    "SOLVE": "Find the answer",
    "SONIC": "Relating to sound",
    "SOUND": "Audible vibration",
    "SPARE": "Extra in reserve",
    "SPEAR": "Long pointed weapon",
    "SPECK": "Tiny spot",
    "SPEED": "Rate of motion",
    "SPELL": "Magic formula",
    "SPEND": "Use money",
    "SPIRE": "Tapering tower",
    "SPOIL": "Ruin",
    "SPRAY": "Fine mist",
    "SQUAT": "Crouching position",
    "SQUID": "Tentacled sea creature",
    "STALE": "No longer fresh",
    "STALK": "Pursue quietly",
    "STALL": "Delay",
    "STAMP": "Mark with ink",
    "STASH": "Hidden store",
    "STEAM": "Water vapor",
    "STEEP": "Sharply inclined",
    "STEER": "Guide direction",
    "STERN": "Strict",
    "STING": "Sharp pain",
    "STOMP": "Heavy footstep",
    "STONY": "Full of stones",
    "STORK": "Long-legged bird",
    "STORM": "Violent weather",
    "STORY": "Narrative account",
    "STOVE": "Cooking appliance",
    "STRAP": "Narrow band",
    "STRAW": "Dried plant stalks",
    "STRAY": "Wander away",
    "STRIP": "Remove covering",
    "STUCK": "Unable to move",
    "STUDY": "Academic work",
    "STUMP": "Tree base",
    "SWAMP": "Waterlogged ground",
    "SWARM": "Large insect group",
    "SWEAR": "Take an oath",
    "SWEEP": "Clean with brush",
    "SWEET": "Sugary taste",
    "SWELL": "Expand in size",
    "SWIRL": "Spiral movement",
    "SWORD": "Long blade weapon",
    "TALON": "Bird's claw",
    "TANGO": "Argentine dance",
    "TAWNY": "Tan-yellow color",
    "TENSE": "Showing strain",
    "THORN": "Sharp plant spike",
    "THROB": "Pulsate",
    "THROW": "Launch through air",
    "THUMB": "Broad first digit",
    "TIARA": "Ornamental headband",
    "TIGER": "Striped big cat",
    "TIGHT": "Firmly fixed",
    "TOAST": "Browned bread",
    "TOKEN": "Symbolic gesture",
    "TOPAZ": "Yellow gemstone",
    "TORCH": "Burning light",
    "TOUGH": "Hard to cut",
    "TOWEL": "Drying cloth",
    "TRAIL": "Rough path",
    "TRAIT": "Characteristic quality",
    "TRAMP": "Wanderer",
    "TRAWL": "Drag-net fishing",
    "TREND": "Current fashion",
    "TRIAL": "Test or hearing",
    "TRIBE": "Social group",
    "TRILL": "Quavering sound",
    "TRIPE": "Stomach lining meat",
    "TROLL": "Mythological creature",
    "TROOP": "Military unit",
    "TROUT": "Freshwater fish",
    "TROVE": "Cache of treasure",
    "TRUCE": "Ceasefire",
    "TUBER": "Underground stem",
    "TULIP": "Spring bulb flower",
    "TUNIC": "Loose garment",
    "TWIRL": "Spin around",
    "TWIST": "Wind together",
    "ULCER": "Open sore",
    "UNCLE": "Parent's brother",
    "UNIFY": "Bring together",
    "UNION": "Combined group",
    "UNITE": "Join together",
    "USURP": "Seize without right",
    "UTTER": "Speak",
    "VENOM": "Toxic secretion",
    "VERSE": "Poetry lines",
    "VIGOR": "Physical energy",
    "VIOLA": "Stringed instrument",
    "VIPER": "Venomous snake",
    "VISTA": "Wide view",
    "VIVID": "Bright and clear",
    "VIXEN": "Female fox",
    "VOTER": "Election participant",
    "WAGER": "Place a bet",
    "WAIST": "Middle of body",
    "WALTZ": "Ballroom dance",
    "WEARY": "Extremely tired",
    "WEDGE": "V-shaped tool",
    "WEIRD": "Strangely unusual",
    "WINCH": "Hoisting device",
    "WITTY": "Cleverly funny",
    "WRATH": "Fierce anger",
    "YEARN": "Long for",
    "YODEL": "Alpine singing style",
    "YOUNG": "Early in life",
    "YOUTH": "Young people",
    "ZONAL": "Divided into zones",

    # ── 6-letter words ──────────────────────────────────────────────────────
    "ABLAZE": "On fire",
    "ABSORB": "Take in",
    "ACCENT": "Speech inflection",
    "ACCORD": "Mutual agreement",
    "ACCRUE": "Build up over time",
    "ACQUIT": "Declare not guilty",
    "ACTIVE": "Energetically moving",
    "ADVENT": "Arrival of something",
    "AERIAL": "From the air",
    "AFFIRM": "Declare firmly",
    "AFFORD": "Have enough for",
    "AFLOAT": "Floating on water",
    "AFIELD": "Far from home",
    "AGENDA": "Meeting plan",
    "AGGRIEVE": "Cause distress",
    "ALBINO": "Lacking pigment",
    "ALCOVE": "Recessed nook",
    "ALLURE": "Attractive quality",
    "ALMOST": "Very nearly",
    "ALPINE": "Mountain-related",
    "ALWAYS": "At all times",
    "AMBLER": "Gentle walker",
    "AMBUSH": "Surprise attack",
    "ANCHOR": "Ship's mooring weight",
    "ANNUAL": "Yearly",
    "ANTLER": "Deer horn",
    "ANTICS": "Playful behavior",
    "ANTLER": "Deer's branching horn",
    "APLOMB": "Poise and confidence",
    "APPEASE": "Satisfy demands",
    "ARCHER": "Bow shooter",
    "ARDENT": "Passionate",
    "ARMADA": "Fleet of ships",
    "ARTERY": "Blood vessel",
    "ARTFUL": "Crafty",
    "ASLEEP": "In slumber",
    "ASTERN": "Toward ship's rear",
    "ATTAIN": "Reach a goal",
    "ATTEST": "Certify",
    "AUTUMN": "Fall season",
    "AVENGE": "Take revenge",
    "AVERSE": "Strongly opposed",
    "AVIARY": "Bird enclosure",
    "AWNING": "Outdoor shade",
    "BABBLE": "Talk fast nonsense",
    "BADGER": "Burrowing mammal",
    "BALLET": "Classical dance",
    "BAMBOO": "Tall grass plant",
    "BANANA": "Yellow curved fruit",
    "BARLEY": "Brewing grain",
    "BEACON": "Signal light",
    "BEAKER": "Laboratory glass",
    "BECKON": "Summon with gesture",
    "BEDLAM": "Noisy confusion",
    "BEFALL": "Happen to",
    "BEMOAN": "Express sorrow",
    "BENIGN": "Harmless",
    "BIRCH": "White-barked tree",
    "BLIGHT": "Disease that kills plants",
    "BLITHE": "Casual or carefree",
    "BOGGLE": "Overwhelm",
    "BONNET": "Old-fashioned hat",
    "BORING": "Dull",
    "BOTANY": "Study of plants",
    "BOUNCE": "Spring back",
    "BREEZE": "Light wind",
    "BRIDGE": "Spanning structure",
    "BRIDLE": "Horse headgear",
    "BLIGHT": "Harmful disease",
    "BRUTAL": "Savage",
    "BUCKLE": "Belt fastener",
    "BUFFET": "Blow or food counter",
    "BUMBLE": "Blunder about",
    "BUNDLE": "Items wrapped together",
    "BURROW": "Animal tunnel",
    "BUTTER": "Dairy spread",
    "CACTUS": "Desert plant",
    "CANOPY": "Overhead covering",
    "CANTER": "Moderate horse gait",
    "CANVASS": "Survey opinions",
    "CASKET": "Small chest",
    "CASTLE": "Fortified dwelling",
    "CAVERN": "Large cave",
    "CELLAR": "Underground room",
    "CEMENT": "Binding material",
    "CENSUS": "Population count",
    "CEREAL": "Breakfast grain",
    "CHANGE": "Make different",
    "CHOICE": "Selection made",
    "CHROME": "Shiny metal finish",
    "CIRCLE": "Round shape",
    "CIPHER": "Secret code",
    "CLAMOR": "Noisy demand",
    "CLOVER": "Three-leaf plant",
    "COBBLE": "Round paving stone",
    "COCOON": "Silk larva wrap",
    "COFFER": "Strong chest",
    "COHORT": "Group of associates",
    "COMBAT": "Armed fight",
    "COMET": "Cosmic ice ball",
    "COMPLY": "Follow rules",
    "CONCUR": "Agree",
    "CONDOR": "Large vulture",
    "CONSUL": "Official ambassador",
    "CONVOY": "Protected group",
    "COPPER": "Reddish metal",
    "CORNER": "Where walls meet",
    "CORONA": "Sun's outer atmosphere",
    "COSTLY": "Expensive",
    "COTTON": "Natural fiber",
    "COUGAR": "Mountain lion",
    "CRAGGY": "Rough and rugged",
    "CRATER": "Bowl-shaped hollow",
    "CREST": "Top of hill",
    "CRIMSON": "Deep red",
    "CRUISE": "Ocean voyage",
    "CRUMBLE": "Fall apart",
    "CURFEW": "Required stay-in",
    "DAGGER": "Short blade",
    "DAMAGE": "Harm done",
    "DAMPEN": "Make slightly wet",
    "DARING": "Bold and risky",
    "DEBRIS": "Scattered fragments",
    "DECENT": "Adequate and proper",
    "DECREE": "Official order",
    "DEFEAT": "Win against",
    "DEFECT": "Flaw",
    "DEFEND": "Protect",
    "DEFILE": "Pollute",
    "DEFORM": "Distort shape",
    "DELUGE": "Heavy flood",
    "DENOTE": "Indicate",
    "DESERT": "Arid wasteland",
    "DEVOID": "Completely lacking",
    "DEVOUT": "Deeply religious",
    "DIFFER": "Be unlike",
    "DIGGER": "Excavating tool",
    "DILUTE": "Weaken with water",
    "DIMPLE": "Small indentation",
    "DINGHY": "Small boat",
    "DONKEY": "Domestic ass",
    "DOTTED": "Covered in spots",
    "DOUBLY": "Twice over",
    "DRAGON": "Mythical fire creature",
    "DRENCH": "Soak thoroughly",
    "DRIVEN": "Motivated",
    "DRIZZLE": "Light rain",
    "DUSTED": "Lightly coated",
    "EARTHY": "Like soil",
    "EFFUSE": "Give off freely",
    "EGRESS": "Exit route",
    "ELIXIR": "Magic cure",
    "EMBARK": "Start a journey",
    "EMBLEM": "Symbol",
    "EMPATH": "One who feels others",
    "EMPIRE": "Wide dominion",
    "EMPLOY": "Give work to",
    "ENAMEL": "Hard coating",
    "ENDURE": "Withstand",
    "ENERGY": "Power to work",
    "ENGAGE": "Involve",
    "ENGINE": "Power machine",
    "ENIGMA": "Puzzling mystery",
    "ENTICE": "Tempt",
    "ERRANT": "Wandering wrongly",
    "ESCAPE": "Get away from",
    "ESTEEM": "High regard",
    "EVOLVE": "Change gradually",
    "EXCITE": "Stimulate",
    "EXEMPT": "Free from rule",
    "EXHORT": "Urge strongly",
    "EXPEL": "Force out",
    "EXPOSE": "Reveal",
    "EXTEND": "Stretch out",
    "FAMINE": "Extreme food shortage",
    "FARMER": "Agricultural worker",
    "FATHOM": "Understand fully",
    "FELINE": "Cat-related",
    "FIDGET": "Move restlessly",
    "FIERCE": "Violently aggressive",
    "FILTER": "Strain liquid",
    "FINGER": "Hand digit",
    "FJORD": "Coastal inlet",
    "FLEDGE": "Grow feathers",
    "FLIMSY": "Thin and fragile",
    "FLINCH": "Shrink back",
    "FLOWER": "Plant bloom",
    "FLUENT": "Speaking smoothly",
    "FLUTTER": "Move with quick beats",
    "FOREST": "Dense tree area",
    "FORMAL": "Following rules",
    "FOSSIL": "Preserved ancient life",
    "FRENZY": "Wild excitement",
    "FRESCO": "Wall painting",
    "FROZEN": "Turned to ice",
    "FUMBLE": "Handle clumsily",
    "FUNGUS": "Mold or mushroom",
    "GALLOP": "Fast horse gait",
    "GARLIC": "Pungent bulb",
    "GARNET": "Red gemstone",
    "GEYSER": "Hot spring spout",
    "GIBBER": "Talk fast nonsense",
    "GIDDY": "Lightheaded",
    "GIBBET": "Gallows structure",
    "GIRDLE": "Encircling band",
    "GLIDER": "Engineless aircraft",
    "GOBLIN": "Mischievous spirit",
    "GORILLA": "Great ape",
    "GOSSIP": "Idle talk",
    "GRAVEL": "Small stones",
    "GRIEVE": "Feel sorrow",
    "GRILLE": "Metal grating",
    "GROTTO": "Small cave",
    "GROUSE": "Complain",
    "GROVEL": "Lie face down",
    "GROWTH": "Increase in size",
    "GRUMPY": "Bad tempered",
    "GUTTER": "Drainage channel",
    "HAMLET": "Small village",
    "HAMPER": "Hinder",
    "HARBOR": "Sheltered port",
    "HARDEN": "Make firm",
    "HARROW": "Farm leveling tool",
    "HAZARD": "Dangerous risk",
    "HELMET": "Protective headgear",
    "HERALD": "Messenger",
    "HERMIT": "Recluse",
    "HEROIC": "Showing bravery",
    "HICCUP": "Spasm of diaphragm",
    "HINDER": "Obstruct",
    "HOLLOW": "Empty inside",
    "HONEST": "Truthful",
    "HORNET": "Large wasp",
    "HUNGER": "Need for food",
    "HUNTER": "One who pursues game",
    "HURDLE": "Jump over obstacle",
    "IGNITE": "Set on fire",
    "ILLICIT": "Unlawful",
    "IMMUNE": "Protected from",
    "IMPACT": "Striking force",
    "IMPEDE": "Block progress",
    "INDENT": "Set in from margin",
    "INFUSE": "Steep in liquid",
    "INJECT": "Force liquid in",
    "INSECT": "Six-legged creature",
    "INSIDE": "Interior",
    "INSIST": "Demand firmly",
    "INTAKE": "Amount taken in",
    "INVADE": "Enter by force",
    "ISLAND": "Land surrounded by water",
    "JACKAL": "Wild canine",
    "JANGLE": "Make discordant sound",
    "JARGON": "Specialized language",
    "JOSTLE": "Push and shove",
    "JOVIAL": "Cheerful",
    "JUNGLE": "Dense tropical forest",
    "KERNEL": "Seed center",
    "KITTEN": "Young cat",
    "KNIGHT": "Armored horseman",
    "LAGOON": "Shallow coastal water",
    "LAMENT": "Express grief",
    "LANTERN": "Portable light",
    "LATHER": "Soap foam",
    "LAVISH": "Generous and luxurious",
    "LEGACY": "What is handed down",
    "LEGEND": "Traditional story",
    "LINGER": "Stay longer",
    "LIQUID": "Flowing substance",
    "LISTEN": "Pay attention",
    "LIZARD": "Scaly reptile",
    "LOCKET": "Small jewelry case",
    "LOFTY": "High and noble",
    "LOOSEN": "Make less tight",
    "LOUNGE": "Relaxation room",
    "LUCENT": "Shining",
    "LUMBER": "Timber for building",
    "LUNGES": "Sudden movements",
    "LURID": "Shockingly vivid",
    "LUSTER": "Soft shine",
    "MAGNET": "Attracting device",
    "MAMMAL": "Warm-blooded animal",
    "MANTLE": "Cloak-like layer",
    "MARBLE": "Hard patterned stone",
    "MARTEN": "Tree-climbing mammal",
    "MARVEL": "Wonder at",
    "MEADOW": "Open grassy field",
    "MEDLEY": "Mixed variety",
    "MENTOR": "Experienced guide",
    "METEOR": "Space rock in sky",
    "MILLET": "Grain crop",
    "MINGLE": "Mix socially",
    "MIRROR": "Reflective surface",
    "MISTLE": "Parasitic plant",
    "MITTEN": "Fingerless glove",
    "MODEST": "Not boastful",
    "MONKEY": "Tree-dwelling primate",
    "MORTAR": "Binding paste",
    "MORSEL": "Small bite",
    "MOSAIC": "Tile picture",
    "MOTTLE": "Irregular pattern",
    "MUFFIN": "Small cake",
    "MUMBLE": "Speak unclearly",
    "MUSCLE": "Body tissue for movement",
    "MUTTON": "Sheep meat",
    "MYRTLE": "Aromatic shrub",
    "NARROW": "Not wide",
    "NATIVE": "Born locally",
    "NATURE": "Natural world",
    "NEEDLE": "Sewing point",
    "NETTLE": "Stinging plant",
    "NIMBLE": "Quick and light",
    "NUZZLE": "Rub gently",
    "NYMPH": "Water spirit",
    "OBJECT": "Physical thing",
    "OBTAIN": "Acquire",
    "OFFEND": "Cause displeasure",
    "ONLINE": "Connected to internet",
    "OPAQUE": "Not transparent",
    "OPPOSE": "Be against",
    "ORANGE": "Citrus fruit",
    "ORCHID": "Exotic flower",
    "ORDEAL": "Harsh experience",
    "ORIGIN": "Starting point",
    "OSPREY": "Fish-eating hawk",
    "OUNCE": "Small weight unit",
    "OUTRUN": "Exceed in speed",
    "OYSTER": "Pearl-producing shellfish",
    "PADDLE": "Short oar",
    "PAMPER": "Treat indulgently",
    "PANDER": "Cater to wishes",
    "PANTRY": "Food storage room",
    "PARROT": "Colorful talking bird",
    "PARSLEY": "Herb garnish",
    "PATROL": "Guard rounds",
    "PATTER": "Quick light steps",
    "PEBBLE": "Small smooth stone",
    "PELLET": "Small ball",
    "PENCIL": "Writing instrument",
    "PEPPER": "Spice or vegetable",
    "PETREL": "Seabird",
    "PILLAR": "Supporting column",
    "PISTOL": "Short firearm",
    "PIRATE": "Sea robber",
    "PLAINS": "Open flat land",
    "PLANET": "Orbiting world",
    "PLOVER": "Shore bird",
    "PLUNGE": "Dive steeply",
    "POCKET": "Small bag in garment",
    "POLLEN": "Plant fertilizing dust",
    "POPLAR": "Tall thin tree",
    "PORTAL": "Gateway",
    "POTTER": "Ceramic craftsman",
    "POUNCE": "Jump on suddenly",
    "POWDER": "Fine dry particles",
    "PRAISE": "Express approval",
    "PREACH": "Deliver sermon",
    "PREFER": "Choose above",
    "PREVAIL": "Gain victory",
    "PRIEST": "Religious minister",
    "PROFIT": "Financial gain",
    "PROMPT": "On time",
    "PUFFIN": "Seabird",
    "PURSUE": "Chase after",
    "PUZZLE": "Difficult problem",
    "QUARTZ": "Crystalline mineral",
    "RABBIT": "Burrowing mammal",
    "RAPIDS": "Fast river section",
    "RASCAL": "Mischief-maker",
    "RATION": "Fixed allowance",
    "RAVINE": "Deep narrow valley",
    "RECORD": "Document",
    "REDUCE": "Make smaller",
    "REFUGE": "Safe shelter",
    "REJECT": "Turn down",
    "RESCUE": "Save from danger",
    "RESULT": "Final outcome",
    "REVEAL": "Make known",
    "RIDDLE": "Puzzling question",
    "RIPPLE": "Small wave",
    "RITUAL": "Ceremonial act",
    "ROBUST": "Strong",
    "ROCKET": "Space propulsion",
    "RODENT": "Gnawing mammal",
    "RUCKUS": "Commotion",
    "RUMBLE": "Low rolling sound",
    "RUSTLE": "Soft crackling sound",
    "SADDLE": "Rider's seat",
    "SALMON": "Pink-fleshed fish",
    "SAMPLE": "Small portion",
    "SAVAGE": "Fierce",
    "SCATTER": "Spread widely",
    "SCHEME": "Plan",
    "SCORPION": "Venomous arachnid",
    "SCORCH": "Burn slightly",
    "SCRAWL": "Write messily",
    "SCREEN": "Viewing surface",
    "SCULPT": "Carve or shape",
    "SEALED": "Closed airtight",
    "SEARCH": "Look carefully",
    "SEASON": "Time of year",
    "SECURE": "Make safe",
    "SERENE": "Calm and peaceful",
    "SETTLE": "Resolve",
    "SHADOW": "Area blocking light",
    "SHIVER": "Tremble from cold",
    "SHOVEL": "Digging tool",
    "SIGNAL": "Communication sign",
    "SILVER": "Precious white metal",
    "SIMPLE": "Not complex",
    "SIZZLE": "Frying sound",
    "SKETCH": "Quick drawing",
    "SLEEPY": "Drowsy",
    "SLIVER": "Thin slice",
    "SMOKEY": "Filled with smoke",
    "SNATCH": "Grab quickly",
    "SNUGGLE": "Cuddle",
    "SOCKET": "Plug receptacle",
    "SOGGY": "Wet and soft",
    "SOLEMN": "Serious and sincere",
    "SOOTHE": "Calm",
    "SORROW": "Deep sadness",
    "SPARSE": "Thinly spread",
    "SPIDER": "Eight-legged creature",
    "SPIRIT": "Immaterial essence",
    "SPLASH": "Water scatter",
    "SPLICE": "Join ropes",
    "SPRAWL": "Spread out",
    "SPRING": "Season of growth",
    "SPROUT": "New plant shoot",
    "SQUALL": "Sudden storm",
    "SQUIRE": "Knight's attendant",
    "STABLE": "Horse barn",
    "STEALTH": "Careful concealment",
    "STENCH": "Bad smell",
    "STIPPLE": "Dotting technique",
    "STOLEN": "Taken wrongly",
    "STRAND": "Thread or beach",
    "STREAK": "Fast movement",
    "STROKE": "Single movement",
    "STROLL": "Leisurely walk",
    "STRONG": "Powerful",
    "SUBTLE": "Hard to detect",
    "SUMMIT": "Highest point",
    "SUNDRY": "Various",
    "SUNLIT": "Bathed in sunlight",
    "SWIVEL": "Rotate on pivot",
    "SYMBOL": "Meaningful sign",
    "SYSTEM": "Organized structure",
    "TANGLE": "Twist into knots",
    "TARTAN": "Plaid wool cloth",
    "TAVERN": "Public house",
    "TENDER": "Gentle or soft",
    "TEPID": "Lukewarm",
    "THATCH": "Roof grass",
    "THEORY": "Explanatory idea",
    "THICKET": "Dense shrub area",
    "THRASH": "Beat vigorously",
    "THRONG": "Dense crowd",
    "THRUST": "Push forcefully",
    "TICKLE": "Touch lightly",
    "TIMBER": "Building wood",
    "TINSEL": "Shiny decoration",
    "TOPPLE": "Fall over",
    "TORRENT": "Fast stream",
    "TOUCAN": "Tropical bird",
    "TOWERING": "Very tall",
    "TRAITOR": "One who betrays",
    "TREBLE": "Triple",
    "TREMOR": "Small earthquake",
    "TRENCH": "Long ditch",
    "TRIFLE": "Small matter",
    "TUNDRA": "Arctic plain",
    "TUNNEL": "Underground passage",
    "TURBAN": "Head wrap",
    "TURKEY": "Large game bird",
    "TURNIP": "Root vegetable",
    "TWITCH": "Quick jerk",
    "TYPHOON": "Tropical storm",
    "UDDERS": "Milk glands",
    "UNKEMPT": "Untidy",
    "UPLIFT": "Raise up",
    "URGENT": "Requiring fast action",
    "USABLE": "Fit for use",
    "VACANT": "Empty",
    "VALLEY": "Land between hills",
    "VANISH": "Disappear",
    "VARIED": "Diverse",
    "VELVET": "Smooth soft fabric",
    "VERMIN": "Pest animals",
    "VESSEL": "Hollow container",
    "VICTIM": "One who suffers",
    "VIOLET": "Purple flower",
    "VIRTUE": "Moral excellence",
    "VIVIFY": "Make lively",
    "VULTURE": "Scavenging bird",
    "WALLOW": "Roll in mud",
    "WALRUS": "Tusked marine mammal",
    "WANDER": "Roam aimlessly",
    "WEAPON": "Tool for combat",
    "WEASEL": "Slender carnivore",
    "WEAVER": "Loom operator",
    "WHIRL": "Spinning motion",
    "WICKER": "Woven twigs",
    "WILLOW": "Drooping-branch tree",
    "WITHER": "Dry up",
    "WIZARD": "Magic practitioner",
    "WONDER": "Feel amazed",
    "WOODEN": "Made of wood",
    "WRITHE": "Twist in pain",
    "YELLOW": "Sunflower color",
    "YEOMAN": "Free farmer",
    "ZEALOT": "Extreme follower",
    "ZIGZAG": "Back-and-forth path",

    # ── 7-letter words ──────────────────────────────────────────────────────
    "ABANDON": "Give up completely",
    "ABILITY": "Power to do",
    "ABSENCE": "Not being present",
    "ABSOLVE": "Free from blame",
    "ACCLAIM": "Public praise",
    "ACCOUNT": "Explanatory report",
    "ACROBAT": "Gymnastic performer",
    "ADAMANT": "Firmly insistent",
    "ADDRESS": "Where one lives",
    "ADMIRAL": "Senior naval officer",
    "ANCIENT": "Very old",
    "ANDROID": "Human-like robot",
    "ANNEX": "Attached building",
    "ANXIETY": "Worry feeling",
    "APPRISE": "Inform",
    "APPROVE": "Give consent",
    "ARCHWAY": "Arched entrance",
    "ARID": "Extremely dry",
    "ARMORED": "Wearing protective plates",
    "ARSENAL": "Weapons store",
    "BALANCE": "Even distribution",
    "BAMBOO": "Tropical plant",
    "BANQUET": "Formal feast",
    "BLOSSOM": "Flower on tree",
    "BOTANIC": "Plant-related",
    "BOUQUET": "Bunch of flowers",
    "BRACKET": "Supporting shelf",
    "BRAVERY": "Courageous act",
    "BRIMFUL": "Completely full",
    "BRISTLE": "Short stiff hair",
    "BROADEN": "Make wider",
    "BROTHER": "Male sibling",
    "BUFFALO": "Large bovine",
    "CABINET": "Storage furniture",
    "CALMING": "Reducing anxiety",
    "CAMPING": "Outdoor sleeping",
    "CAPTAIN": "Ship's commander",
    "CAREFUL": "Taking caution",
    "CARIBOU": "Arctic deer",
    "CASCADE": "Waterfall",
    "CHIMNEY": "Smoke vent",
    "CHIPPED": "Slightly broken",
    "CHUCKLE": "Quiet laughter",
    "CIRCUIT": "Electrical path",
    "CLARION": "Clear trumpet",
    "CLEARLY": "Without doubt",
    "CLEANSE": "Purify",
    "CLIMATE": "Weather pattern",
    "CLUSTER": "Tight group",
    "COASTAL": "Near the shore",
    "COBWEBS": "Spider silk",
    "COLLECT": "Gather together",
    "COMBINE": "Join together",
    "COMPOST": "Decayed material",
    "CONDENSE": "Make denser",
    "CONFIRM": "Verify",
    "CONNECT": "Join",
    "CONTOUR": "Outline shape",
    "CONVERT": "Change form",
    "COWBIRD": "Brood parasite bird",
    "CRYSTAL": "Transparent mineral",
    "CURIOUS": "Eager to know",
    "CURRENT": "Flow of water",
    "CURTAIN": "Hanging screen",
    "CUSHION": "Soft padding",
    "DARLING": "Term of affection",
    "DECIMAL": "Base-ten number",
    "DECLARE": "Announce formally",
    "DEFLECT": "Turn aside",
    "DEPOSIT": "Place safely",
    "DESCENT": "Going downward",
    "DISTANT": "Far away",
    "DOLPHIN": "Marine mammal",
    "DROUGHT": "Long dry period",
    "DURABLE": "Long lasting",
    "EARNEST": "Sincere",
    "ECOLOGY": "Study of environment",
    "ELASTIC": "Stretchy",
    "ELEGANT": "Tasteful style",
    "EMPEROR": "Supreme ruler",
    "ENCHANT": "Cast a spell",
    "ENCRYPT": "Encode data",
    "ENFORCE": "Compel obedience",
    "ENHANCE": "Make better",
    "ENLARGE": "Make bigger",
    "EROSION": "Wearing away",
    "ETERNAL": "Lasting forever",
    "EVENING": "After sunset",
    "EVIDENT": "Clearly seen",
    "EXHAUST": "Use up completely",
    "EXPLAIN": "Make clear",
    "EXPLORE": "Investigate",
    "EXPRESS": "Communicate",
    "EXTREME": "At the limit",
    "FACTORY": "Manufacturing plant",
    "FANTASY": "Imaginative fiction",
    "FASHION": "Current style",
    "FEATHER": "Bird plume",
    "FERTILE": "Productive soil",
    "FESTIVE": "Celebratory",
    "FICTION": "Invented narrative",
    "FIERCE": "Violently intense",
    "FJORD": "Mountain inlet",
    "FLICKER": "Flash unsteadily",
    "FLUTTER": "Move wings rapidly",
    "FOOTWAY": "Walking path",
    "FORLORN": "Lonely and sad",
    "FORMULA": "Prescribed method",
    "FORWARD": "In front direction",
    "FRECKLE": "Small skin spot",
    "FURNACE": "Heating device",
    "GATEWAY": "Entrance point",
    "GLACIER": "Slow ice river",
    "GLIMPSE": "Brief look",
    "GLISTEN": "Shine wetly",
    "GRANITE": "Hard rock",
    "GRAVITY": "Pulling force",
    "GENUINE": "Authentic",
    "HABITAT": "Natural home",
    "HALLWAY": "Corridor",
    "HARMONY": "Pleasant agreement",
    "HARVEST": "Gather crops",
    "HISTORY": "Record of past",
    "HORIZON": "Sky-earth boundary",
    "IMAGINE": "Form mental image",
    "IMPROVE": "Make better",
    "INSPIRE": "Fill with enthusiasm",
    "INVOLVE": "Include",
    "ISOLATE": "Set apart",
    "JOURNEY": "Long trip",
    "JUSTICE": "Fair treatment",
    "LANDFILL": "Waste site",
    "LANTERN": "Portable lamp",
    "LABORED": "Done with effort",
    "LEOPARD": "Spotted big cat",
    "LIBERTY": "Freedom",
    "LOBSTER": "Clawed crustacean",
    "LOOKOUT": "Watch point",
    "MAGNIFY": "Make appear larger",
    "MAMMOTH": "Extinct elephant",
    "MAPPING": "Creating charts",
    "MARINER": "Sailor",
    "MASSIVE": "Very large",
    "MEADOWS": "Grassy fields",
    "MENTION": "Refer to briefly",
    "MIGRATE": "Move seasonally",
    "MINERAL": "Natural substance",
    "MIRACLE": "Extraordinary event",
    "MONARCH": "King or queen",
    "MORNING": "Before noon",
    "MOSSY": "Covered in moss",
    "MYSTERY": "Unexplained event",
    "NATURAL": "Not artificial",
    "NETWORK": "Interconnected group",
    "NOTABLY": "Remarkably",
    "NOTHING": "Not anything",
    "NUCLEUS": "Central part",
    "NUTSHELL": "In brief",
    "OBSERVE": "Watch carefully",
    "OBVIOUS": "Clearly apparent",
    "OFFERED": "Made available",
    "ONWARDS": "Moving forward",
    "ORBITAL": "Relating to an orbit",
    "PANTHER": "Black leopard",
    "PATTERN": "Repeated design",
    "PENGUIN": "Flightless seabird",
    "PHANTOM": "Ghost",
    "PILGRIM": "Religious traveler",
    "PLATEAU": "Elevated flat land",
    "PLUNDER": "Loot",
    "POSSESS": "Own",
    "POTHOLE": "Road cavity",
    "PRATTLE": "Talk at length",
    "PREDICT": "Forecast",
    "PREPARE": "Get ready",
    "PRESENT": "Here now",
    "PREVENT": "Stop from happening",
    "PRODUCE": "Create goods",
    "PROFILE": "Side view",
    "PROJECT": "Planned work",
    "PROTECT": "Keep safe",
    "PROVIDE": "Supply",
    "PURPOSE": "Reason for action",
    "QUALIFY": "Meet requirements",
    "QUANTUM": "Smallest unit",
    "RADIANT": "Brightly shining",
    "RAMPART": "Defensive wall",
    "RAPIDLY": "Very fast",
    "RECEIVE": "Get",
    "RECOVER": "Get well again",
    "REFLECT": "Mirror back",
    "REFRESH": "Renew",
    "RELEASE": "Let free",
    "REMAINS": "What is left",
    "REQUIRE": "Need",
    "RESHAPE": "Give new form",
    "RESOLVE": "Settle firmly",
    "RESPOND": "Reply",
    "RESTORE": "Return to original",
    "RETREAT": "Go back",
    "REUNION": "Coming back together",
    "RIPPING": "Tearing apart",
    "ROLLING": "Moving in circles",
    "ROOFTOP": "Top of building",
    "RUSHING": "Moving fast",
    "SAILORS": "Ship crew",
    "SALVAGE": "Recover from wreck",
    "SAPPHIRE": "Blue gemstone",
    "SAPLING": "Young tree",
    "SCATTER": "Spread around",
    "SCIENCE": "Systematic knowledge",
    "SEAFLOOR": "Ocean bottom",
    "SEASIDE": "Near the ocean",
    "SECTION": "Part of whole",
    "SEISMIC": "Earthquake-related",
    "SERENADE": "Musical tribute",
    "SERVICE": "Work done for others",
    "SHELTER": "Protective covering",
    "SHIMMER": "Soft flickering light",
    "SILENCE": "Complete quiet",
    "SKILLED": "Highly trained",
    "SKYLINE": "City horizon",
    "SLENDER": "Gracefully thin",
    "SLOPING": "On an incline",
    "SOARING": "Flying high",
    "SOLITARY": "Alone",
    "SPARKLE": "Gleam brightly",
    "SPECIES": "Biological kind",
    "SPINDLE": "Thread twisting tool",
    "SPOTTED": "Marked with dots",
    "SQUIRREL": "Tree-climbing rodent",
    "STRATUM": "Layer",
    "STRETCH": "Extend in length",
    "SUBSIDE": "Sink down",
    "SUBLIME": "Awe-inspiring",
    "SUNRISE": "Dawn",
    "SUPPORT": "Hold up",
    "SUSTAIN": "Keep going",
    "SWALLOW": "Bird or act of ingestion",
    "TANGENT": "Line touching curve",
    "TEMPEST": "Violent storm",
    "TERRAIN": "Land surface",
    "THUNDER": "Storm sound",
    "TIGHTEN": "Make firmer",
    "TOPSOIL": "Upper ground layer",
    "TORRENT": "Fast-flowing water",
    "TOWPATH": "Canal bank path",
    "TRACKER": "One who follows",
    "TRADING": "Exchange of goods",
    "TREMBLE": "Shake with fear",
    "TRICKLE": "Slow thin stream",
    "TRIMMED": "Cut neatly",
    "TRIUMPH": "Great victory",
    "TROUBLE": "Difficulty",
    "TWISTED": "Turned around",
    "UNIFORM": "Standard outfit",
    "UNLEASH": "Set free",
    "UNUSUAL": "Not common",
    "UPGRADE": "Make better",
    "UPSWING": "Rise in activity",
    "VIBRANT": "Full of energy",
    "VILLAGE": "Small settlement",
    "VISIBLE": "Can be seen",
    "VULTURE": "Carrion bird",
    "WARBLER": "Songbird",
    "WEBBING": "Interwoven fabric",
    "WETLAND": "Marshy area",
    "WHISPER": "Soft speech",
    "WILDCAT": "Undomesticated feline",
    "WILLFUL": "Stubborn",
    "WINDMILL": "Wind-powered grinder",
    "WINDING": "Following curves",
    "WITNESS": "See firsthand",
    "WRITTEN": "In writing",

    # ── 8-letter words ──────────────────────────────────────────────────────
    "ABSOLUTE": "Complete",
    "ABUNDANT": "Plentiful",
    "ACCURATE": "Free from error",
    "ACHIEVED": "Successfully done",
    "ACTIVATE": "Set in motion",
    "ADDITION": "Something added",
    "ADJACENT": "Next to",
    "ALTITUDE": "Height above sea level",
    "ANALYSIS": "Detailed examination",
    "ANCESTOR": "Forefather",
    "ANCIENT": "Very old",
    "ANNOUNCE": "Make public",
    "ASSEMBLY": "Gathered group",
    "ASTEROID": "Space rock",
    "ATTACHED": "Joined to",
    "AUDIENCE": "Group of listeners",
    "BACKBONE": "Spinal column",
    "BALANCED": "Evenly proportioned",
    "BEDROCK": "Solid rock foundation",
    "BIRDCALL": "Bird's vocal signal",
    "BLIZZARD": "Severe snowstorm",
    "BOUNDARY": "Dividing line",
    "CANYONS": "Deep rock gorges",
    "CAPYBARA": "Large South American rodent",
    "CARDINAL": "Bright red bird",
    "CATAPULT": "Hurling device",
    "CAVALRY": "Mounted soldiers",
    "CEREMONY": "Formal event",
    "CHIPMUNK": "Small striped squirrel",
    "CIRCULAR": "Ring-shaped",
    "CLIMBING": "Going upward",
    "COLOSSAL": "Enormously large",
    "COLORFUL": "Vivid hue",
    "COMMENCE": "Begin",
    "COMPLETE": "Fully done",
    "COMPOSED": "Calm",
    "COMPRESS": "Squeeze together",
    "CONFLICT": "Struggle",
    "CONSERVE": "Save from waste",
    "CONTINUE": "Keep going",
    "CONTRACT": "Binding agreement",
    "CONTRAST": "Difference",
    "CORRIDOR": "Long passage",
    "CREATURE": "Living being",
    "CROSSBOW": "Archery weapon",
    "DARKNESS": "Absence of light",
    "DEADLINE": "Due date",
    "DECREASE": "Become less",
    "DEFINITE": "Clearly fixed",
    "DELICATE": "Fine and fragile",
    "DESCRIBE": "Give account of",
    "DESIGNED": "Planned",
    "DETAILED": "With many specifics",
    "DISCOVER": "Find for first time",
    "DISTINCT": "Clearly different",
    "DOMINANT": "Most powerful",
    "DORMOUSE": "Small hibernating rodent",
    "DRAINAGE": "Water removal system",
    "DURATION": "Length of time",
    "DWELLING": "Residence",
    "DYNAMICS": "Study of forces",
    "ECOYSTEM": "Biological community",
    "EDUCATED": "Having schooling",
    "EMERGING": "Coming into view",
    "ENORMOUS": "Very large",
    "ENTANGLE": "Twist together",
    "ERUPTION": "Volcanic explosion",
    "ESTUARY": "River mouth",
    "EVALUATE": "Judge the value",
    "EXCAVATE": "Dig out",
    "EXEMPLAR": "Model example",
    "EXPONENT": "Power indicator",
    "EXTERNAL": "Outside",
    "FLOODING": "Overflow of water",
    "FLOURISH": "Grow vigorously",
    "FOOTHOLD": "Secure position",
    "FORESTED": "Covered with trees",
    "FRACTION": "Part of a whole",
    "FRAGMENT": "Small piece",
    "FREQUENT": "Happening often",
    "FRONTIER": "Outer boundary",
    "GENERATE": "Produce",
    "GEOLOGIC": "Earth science related",
    "GRADIENT": "Slope measure",
    "GRATEFUL": "Feeling thankful",
    "GRIZZLED": "Gray streaked",
    "GROUNDED": "On the earth",
    "GUIDANCE": "Direction",
    "HARBORED": "Sheltered",
    "HIGHLAND": "Elevated region",
    "HISTORIC": "Important in history",
    "HOMELAND": "Place of origin",
    "HUMIDITY": "Moisture in air",
    "ICEBERG": "Floating ice mass",
    "IDENTIFY": "Recognize",
    "IGNEOUS": "Formed from lava",
    "INACTIVE": "Not doing anything",
    "INCIDENT": "Event",
    "INCREASE": "Make larger",
    "INDICATE": "Show",
    "INFINITE": "Without end",
    "INFORMED": "Having knowledge",
    "INHERENT": "Built in",
    "ISOLATED": "Set apart",
    "LANDMARK": "Notable feature",
    "LATITUDE": "Earth angle measure",
    "LAVENDER": "Purple herb",
    "LEAFY": "Covered in leaves",
    "LIFETIME": "Duration of life",
    "LINGERED": "Stayed on",
    "LISTENER": "One who hears",
    "LOCATION": "Where something is",
    "MAGNETIC": "Attracting force",
    "MAINTAIN": "Keep going",
    "MANGROVE": "Coastal tree",
    "MANIFEST": "Clearly apparent",
    "MAPMAKER": "Cartographer",
    "MARATHON": "Long foot race",
    "MARIGOLD": "Orange flower",
    "MASSIF": "Mountain group",
    "MATERIAL": "Physical substance",
    "MEASURED": "Carefully sized",
    "MEMBRANE": "Thin flexible layer",
    "MOISTURE": "Small water amount",
    "MOLECULE": "Smallest unit",
    "MOMENTUM": "Moving force",
    "MOUNTAIN": "High landform",
    "MOVEMENT": "Act of moving",
    "NAVIGATE": "Find the way",
    "NESTLING": "Young bird",
    "OBSERVED": "Watched carefully",
    "OFFERING": "Something given",
    "OPENNESS": "Lack of restriction",
    "OUTREACH": "Extension of service",
    "OVERFLOW": "Spill over edge",
    "PANORAMA": "Wide scenic view",
    "PARADISE": "Ideal place",
    "PARALLEL": "Always same distance apart",
    "PARTICLE": "Tiny fragment",
    "PASTORAL": "Rural and peaceful",
    "PATIENCE": "Calm waiting",
    "PEACEFUL": "Free from conflict",
    "PEDIMENT": "Triangular gable",
    "PERCEIVE": "Become aware of",
    "PHYSICAL": "Body-related",
    "PILGRIM": "Religious traveler",
    "PINPOINT": "Locate exactly",
    "PLATFORM": "Raised surface",
    "POLISHED": "Made smooth and shiny",
    "POPULATE": "Fill with people",
    "POSSIBLE": "Can happen",
    "POWERFUL": "Having great force",
    "PRISTINE": "Perfectly clean",
    "PROGRESS": "Move forward",
    "PROLIFIC": "Producing abundantly",
    "RADIANCE": "Bright glow",
    "RAINFALL": "Precipitation total",
    "REACHING": "Extending to",
    "REGISTER": "Official record",
    "REGULATE": "Control",
    "RELAXING": "Reducing tension",
    "REMOTELY": "From a distance",
    "REPUBLIC": "Elected government",
    "RESOURCE": "Available supply",
    "RESPONSE": "Reply",
    "RESTLESS": "Unable to be still",
    "REVERSAL": "Turning back",
    "REWARDED": "Given recognition",
    "RHYTHMIC": "Regular beat",
    "RIPARIAN": "River bank related",
    "ROCKFACE": "Vertical cliff",
    "ROTATION": "Turning around axis",
    "RUGGEDLY": "In a tough manner",
    "SANCTIFY": "Make sacred",
    "SANDBANK": "Underwater ridge",
    "SAPPHIRE": "Blue gemstone",
    "SATURATE": "Soak completely",
    "SCAFFOLD": "Temporary structure",
    "SEDIMENT": "Deposited matter",
    "SENTINEL": "Guard",
    "SEQUENCE": "Order of events",
    "SERRATED": "Saw-toothed",
    "SHEDDING": "Losing outer layer",
    "SHIFTING": "Moving gradually",
    "SILENTLY": "Without sound",
    "SIMULATE": "Imitate",
    "SKELETON": "Bone framework",
    "SLIGHTLY": "To a small degree",
    "SNOWFALL": "Amount of snow",
    "SOCIALLY": "In a group",
    "SOLITUDE": "Being alone",
    "SOLUTION": "Answer to problem",
    "SOLVABLE": "Can be solved",
    "SPECTRUM": "Range of frequencies",
    "SPILLWAY": "Overflow channel",
    "SPRINKLE": "Scatter lightly",
    "STANDARD": "Established rule",
    "STEADILY": "In a steady way",
    "SUNLIGHT": "Daylight from sun",
    "SUPERIOR": "Higher in rank",
    "SURVIVAL": "Staying alive",
    "SWIFTLY": "At great speed",
    "SYMPHONY": "Large orchestral work",
    "TEMPORAL": "Related to time",
    "TERRACED": "In stepped levels",
    "THICKET": "Dense bush",
    "THOUSAND": "Number 1000",
    "TOGETHER": "In a group",
    "TOPOLOGY": "Study of shapes",
    "TOWERING": "Extremely tall",
    "TRANSECT": "Cut across",
    "TRAVERSE": "Cross over",
    "TRENDING": "Growing popular",
    "TROPICAL": "Near the equator",
    "TRUSTFUL": "Full of trust",
    "TWILIGHT": "Dim evening light",
    "VOLCANIC": "From a volcano",
    "WANDERER": "One who roams",
    "WAYPOINT": "Navigation marker",
    "WILDLIFE": "Wild animals",
    "YEARLONG": "Lasting all year",
}
